// <auto-generated />
using System;
using InventoryIT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryIT.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20250320192514_UpdateWarehouseAreaMaster")]
    partial class UpdateWarehouseAreaMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryIT.Models.FinancialYear", b =>
                {
                    b.Property<int>("FinanYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanYearId"));

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Creation_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FinancialYearFrom")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("FinancialYearName")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("FinancialYearTo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.HasKey("FinanYearId")
                        .HasName("PK_Financial Year");

                    b.HasIndex("CompId");

                    b.ToTable("FinancialYear", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.ItemCatagory", b =>
                {
                    b.Property<int>("ItemCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCatId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCatagoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Item Catagory Name");

                    b.HasKey("ItemCatId");

                    b.ToTable("Item Catagory", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.ItemCompany", b =>
                {
                    b.Property<int>("ItemComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemComId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation Date Time");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Item Company Name");

                    b.HasKey("ItemComId");

                    b.ToTable("ItemCompany", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.ItemMaster", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CompId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<int>("ItemCatagory")
                        .HasColumnType("int")
                        .HasColumnName("Item Catagory");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Item Code");

                    b.Property<int>("ItemCompany")
                        .HasColumnType("int")
                        .HasColumnName("Item Company");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Item Name");

                    b.Property<int>("ItemSubCatagory")
                        .HasColumnType("int")
                        .HasColumnName("Item SubCatagory");

                    b.Property<int>("ItemType")
                        .HasColumnType("int")
                        .HasColumnName("Item Type");

                    b.Property<int>("ItemUnit1")
                        .HasColumnType("int")
                        .HasColumnName("[Item Unit1");

                    b.Property<int>("ItemUnit2")
                        .HasColumnType("int")
                        .HasColumnName("Item Unit2");

                    b.Property<string>("PartNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("WarehouseArea")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse Area");

                    b.Property<int>("WarehouseLocation")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse Location");

                    b.Property<int>("WarehouseRack")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse Rack");

                    b.Property<int>("WarehouseShelf")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse Shelf");

                    b.HasKey("ItemId");

                    b.ToTable("Item Master", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.ItemSubCatagory", b =>
                {
                    b.Property<int>("ItemSubCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemSubCatId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<int>("ItemMainCatId")
                        .HasColumnType("int");

                    b.Property<string>("SubCatagoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Sub Catagory Name");

                    b.HasKey("ItemSubCatId");

                    b.ToTable("ItemSubCatagory", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.ItemType", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ItemId");

                    b.ToTable("ItemType", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.ItemUnit", b =>
                {
                    b.Property<int>("ItemUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemUnitId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<string>("ItemUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Item Unit Name");

                    b.HasKey("ItemUnitId");

                    b.ToTable("ItemUnit", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastBranch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Branch Name");

                    b.Property<string>("BranchShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Branch Short Name");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Contact Person");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GstNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("GST No");

                    b.Property<decimal?>("MobileNo")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("Mobile No");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Owner Name");

                    b.Property<string>("PanNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PAN No");

                    b.Property<decimal?>("PhoneNo")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("Phone No");

                    b.Property<decimal?>("PinNo")
                        .HasColumnType("numeric(7, 0)")
                        .HasColumnName("PIN No");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BranchId");

                    b.HasIndex("CompId");

                    b.ToTable("Mast_Branch", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastCity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("City Name");

                    b.Property<string>("CityShortName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("City Short Name");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation Datetime");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Mast_City", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastComp", b =>
                {
                    b.Property<int>("CompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("CompShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Comp. Short Name");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Company Name");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Contact Person");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GstNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("GST No");

                    b.Property<decimal?>("MobileNo")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("Mobile No");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Owner Name");

                    b.Property<string>("PanNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("PAN No");

                    b.Property<decimal?>("PhoneNo")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("Phone No");

                    b.Property<decimal?>("PinNo")
                        .HasColumnType("numeric(7, 0)")
                        .HasColumnName("PIN No");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CompId");

                    b.ToTable("Mast_Comp", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastCountry", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Country Name");

                    b.Property<string>("CountryShortName")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Country Short Name");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.HasKey("CountryId");

                    b.ToTable("Mast_Country", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastItemStk", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Stock Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<double?>("BufferStock")
                        .HasColumnType("float")
                        .HasColumnName("Buffer Stock");

                    b.Property<double?>("ClosingQuantity")
                        .HasColumnType("float")
                        .HasColumnName("Closing Quantity");

                    b.Property<int?>("CompId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<double?>("CurrentQuantity")
                        .HasColumnType("float")
                        .HasColumnName("Current Quantity");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int?>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<double?>("Gst")
                        .HasColumnType("float")
                        .HasColumnName("GST%");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double?>("OpeningQuantity")
                        .HasColumnType("float")
                        .HasColumnName("Opening Quantity");

                    b.Property<double?>("OpeningValue")
                        .HasColumnType("float")
                        .HasColumnName("Opening Value");

                    b.Property<double?>("PurchaseRate")
                        .HasColumnType("float")
                        .HasColumnName("Purchase Rate");

                    b.Property<double?>("SalesRate")
                        .HasColumnType("float")
                        .HasColumnName("Sales Rate");

                    b.HasKey("StockId");

                    b.HasIndex("ItemId");

                    b.ToTable("Mast_ItemSTK", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastItemSupplierRate", b =>
                {
                    b.Property<int>("SuppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuppId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationDateTime");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierCompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Supplier Company  Name");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Supplier Name");

                    b.Property<double>("SupplierRate")
                        .HasColumnType("float")
                        .HasColumnName("Supplier Rate");

                    b.HasKey("SuppId");

                    b.HasIndex("ItemId");

                    b.ToTable("Mast_ItemSupplierRate", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.MastState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation Datetime");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("State Name");

                    b.Property<string>("StateShortName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("State Short Name");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("Mast_State", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.SupplierMaster", b =>
                {
                    b.Property<int>("SuppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuppId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CompId")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Contact Person");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created_By");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation_DateTime");

                    b.Property<string>("EmailId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email Id");

                    b.Property<string>("GstNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GST No");

                    b.Property<decimal?>("MobileNo")
                        .HasColumnType("numeric(12, 0)")
                        .HasColumnName("Mobile No");

                    b.Property<decimal?>("PhoneNo")
                        .HasColumnType("numeric(12, 0)")
                        .HasColumnName("Phone No");

                    b.Property<string>("PinNo")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("PIN No");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SupplierGstCertificate")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Supplier GST Certificate");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Supplier Name");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SuppId");

                    b.ToTable("Supplier Master", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.UserMaster", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Person Name");

                    b.Property<DateTime>("UpdationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Updation DateTime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("User Name");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("User Type");

                    b.HasKey("UserId");

                    b.ToTable("UserMaster", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.WarehouseAreaMaster", b =>
                {
                    b.Property<int>("WarehouseAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseAreaId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseAreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Warehouse Area Name");

                    b.Property<int>("WarehouseLocId")
                        .HasColumnType("int");

                    b.HasKey("WarehouseAreaId");

                    b.HasIndex("WarehouseLocId");

                    b.ToTable("Warehouse Area Master", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.WarehouseLocationMaster", b =>
                {
                    b.Property<int>("WarehouseLocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseLocId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Warehouse Name");

                    b.HasKey("WarehouseLocId");

                    b.ToTable("Warehouse Location Master", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.WarehouseRackMaster", b =>
                {
                    b.Property<int>("WarehouseRackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseRackId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseAreaId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseLocId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseRackName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Warehouse Rack Name");

                    b.HasKey("WarehouseRackId");

                    b.ToTable("Warehouse Rack Master", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.WarehouseShelfMaster", b =>
                {
                    b.Property<int>("WarehouseShelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseShelfId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("Created By");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Creation DateTime");

                    b.Property<int>("FinanYearId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseAreaId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseLocId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseRackId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseShelfName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Warehouse Shelf Name");

                    b.HasKey("WarehouseShelfId");

                    b.ToTable("Warehouse Shelf Master", (string)null);
                });

            modelBuilder.Entity("InventoryIT.Models.FinancialYear", b =>
                {
                    b.HasOne("InventoryIT.Models.MastComp", "Comp")
                        .WithMany("FinancialYears")
                        .HasForeignKey("CompId")
                        .IsRequired()
                        .HasConstraintName("fk_FinanCompId");

                    b.Navigation("Comp");
                });

            modelBuilder.Entity("InventoryIT.Models.MastBranch", b =>
                {
                    b.HasOne("InventoryIT.Models.MastComp", "Comp")
                        .WithMany("MastBranches")
                        .HasForeignKey("CompId")
                        .IsRequired()
                        .HasConstraintName("fk_CompId");

                    b.Navigation("Comp");
                });

            modelBuilder.Entity("InventoryIT.Models.MastCity", b =>
                {
                    b.HasOne("InventoryIT.Models.MastState", "State")
                        .WithMany("MastCities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK_Mast_City_StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("InventoryIT.Models.MastItemStk", b =>
                {
                    b.HasOne("InventoryIT.Models.ItemMaster", "Item")
                        .WithMany("MastItemStks")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventoryIT.Models.MastItemSupplierRate", b =>
                {
                    b.HasOne("InventoryIT.Models.ItemMaster", "Item")
                        .WithMany("MastItemSupplierRates")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemId_ItemSupplier");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventoryIT.Models.MastState", b =>
                {
                    b.HasOne("InventoryIT.Models.MastCountry", "Country")
                        .WithMany("MastStates")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_Mast_State_CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("InventoryIT.Models.WarehouseAreaMaster", b =>
                {
                    b.HasOne("InventoryIT.Models.WarehouseLocationMaster", "WarehouseLocationMaster")
                        .WithMany("WarehouseAreaMaster")
                        .HasForeignKey("WarehouseLocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarehouseLocationMaster");
                });

            modelBuilder.Entity("InventoryIT.Models.ItemMaster", b =>
                {
                    b.Navigation("MastItemStks");

                    b.Navigation("MastItemSupplierRates");
                });

            modelBuilder.Entity("InventoryIT.Models.MastComp", b =>
                {
                    b.Navigation("FinancialYears");

                    b.Navigation("MastBranches");
                });

            modelBuilder.Entity("InventoryIT.Models.MastCountry", b =>
                {
                    b.Navigation("MastStates");
                });

            modelBuilder.Entity("InventoryIT.Models.MastState", b =>
                {
                    b.Navigation("MastCities");
                });

            modelBuilder.Entity("InventoryIT.Models.WarehouseLocationMaster", b =>
                {
                    b.Navigation("WarehouseAreaMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
